CC=g++
CFLAGS=-Wall -std=c++11

mini-project: main.cpp user.cpp userArray.cpp date.cpp book.cpp bookArray.cpp librarySystem.cpp
	$(CC) -o main.exe main.cpp user.cpp userArray.cpp date.cpp book.cpp bookArray.cpp librarySystem.cpp